### ISSUE TITLE
Iteration Plan June 2020

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-hexeditor#48]
# Plan Items
Below is a summary of the top level plan items.

Legend of annotations:
Mark | Description
-------|--------------
🏃‍♂️ | work in progress
🔎| researching
💪| stretch goal

## Features

- [x]  Ability to edit the bytes in the middle column and modify the file #17
- [x] Ability to edit the decoded text in the right column and modify the file. #17
- [ ] 💪 Ability to edit inside the data inspector #17
## Bugs / Fixes
- [x] Files over 18MB couldn't be opened #3 
- [x] Focus is difficult to see #24 
- [x] Data inspector font can appear fuzzy #35

**Comment by lramos15** [comment]
Version 1.1 has been released 🎉🎉🎉.
