### ISSUE TITLE
Iteration Plan July 2020

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-hexeditor#76]
# Plan Items
Below is a summary of the top level plan items.

Legend of annotations:
Mark | Description
-------|--------------
🏃‍♂️ | work in progress
🔎| researching
💪| stretch goal

## Features
- [X] Implement filewatching
- [X]  Support selecting multiple cells
- [x]  Support copy and paste
- [x]  Add the ability to search #49 #45 
- [x]  Find + Replace
## Bugs / Fixes
- [x] Selection not persisted on switching tabs #81
- [x] Improper UTF-8 decoding https://github.com/microsoft/vscode-hexeditor/issues/84 
- [x] Hex section does not allow editing with numeric pad #87 
- [x] Mutli Select not preserved upon scroll / tab switch https://github.com/microsoft/vscode-hexeditor/issues/95
## Pull Requests to Review
- [x] Improved cell selection https://github.com/microsoft/vscode-hexeditor/pull/92

**Comment by lramos15** [comment]
Version 1.2.0 released 🎉🎉🎉
